### ISSUE TITLE
tilt-schema.json link needs to be updated

### ISSUE THREAD

**Issue by dittmanndennis** [Transparency-Information-Language/schema#1]
https://github.com/Transparency-Information-Language/schema/blob/master/documentation/markdown/tilt-schema-properties-meta.md

**Comment by eliasgruenewald** [comment]
What exactly do you mean by that?

**Comment by dittmanndennis** [comment]
https://github.com/Transparency-Information-Language/schema/blob/master/documentation/out/tilt-schema.json
this link isn't working anymore
